name: casino_test
description: Casino test application

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">= 3.0.0 < 4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  http: ^0.13.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.4.0
  material_design_icons_flutter: ^6.0.7096
  stream_transform: ^2.1.0

dev_dependencies:
  build_runner: ^2.0.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
